# Additional questions 

It is always important to learn how to solve questions out of the original context of the material taught. After completing this course you should now be able to answer any of these questions.

## Questions

1. Calculate the entropy change when 2.50 mol of mercury vaporises at its boiling point of 356.55 ºC. Δ~vap~H^⦵^ = + 59.229 kJ mol^−1^.

2. Calculate the free energy change at 25 ºC and 250 ºC for the following reaction:

:::center
MgO (s) + CO (g) ⟶ Mg (s) + CO~2~ (g)
:::

|| Δ~f~H^⦵^ | S^⦵^~m~  J K^−1^ mol^−1^|   C~p~ / J K^−1^ mol^−1^|
|:----:|:----:|:----:|:----:|
|MgO (s) | -601.7 | 26.9 | 37.2 |
|CO (g) | -110.5 | 197.7 | 29.1 |
| Mg (s) | 0 | 32.7 | 24.9 |
| CO~2~ (g) | -393.5 | 213.7 | 37.1 |

State what assumptions you have made.

3. For the reaction:

:::center
A + B ⇌ 2C
:::

Determine the equilibrium concentration of C if the Gibbs energy for the reaction at 20 ºC is −40.0 kJ mol^−1^ and at equilibrium the concentration of A is 0.0500 mol dm^−3^ and B is 0.0450 mol dm^−3^.

4. The Clausius-Clapeyron equation can be used to determine the enthalpy of vaporisation:

\begin{equation*}
\ln p = -\frac{\Delta _{\textrm{vap}}H}{RT}+C
\end{equation*}

Given the data for ethyl acetate (Table \@ref(tab:ethylacetatedata)), determine the enthalpy of vaporization of ethyl acetate, and consequently determine the boiling point (at 1 bar).

Table: (\#tab:ethylacetatedata)  The equilibrium vapour pressure of ethyl acetate at differing temperatures.

| T / ºC | p / 10^3^ Pa |
|:-----:|:-----:|
| 9.1 | 5.304 |
| 27.4 | 13.33 |
| 59.3 | 53.31 |
| 77.1 | 101.32 |
| 100.6 | 202.6 |
| 136.6 | 506.7 |

5. Determine the equilibrium constant for the following reaction at 150 oC, 
:::center
N~2~O~5~ (g) ⟶ NO~2~ (g) + NO (g) + O~2~ (g)
:::

|| Δ~f~H^⦵^ | S^⦵^~m~  J K^−1^ mol^−1^|   C~p~ / J K^−1^ mol^−1^|
|:----:|:----:|:----:|:----:|
| NO (g) | +90.25 | 210.76 | 29.844 |
| NO~2~ (g) | +33.18 | 240.06 | 37.20 |
| N~2~O~5~ (g) | +11.3 |355.7 | 84.5 |
| O~2~ | - | 205.138 | 29.355 |

6. How much energy is released when 4.60 g of sodium reacts with excess water to give NaOH (aq) & H~2~ (g)?

Δ~f~H^⦵^~NaOH~ = −425.61 kJ mol^−1^ 

Δ~f~H^⦵^~H2O~ = −285.83 kJ mol^−1^

## Answers

1. 235 J K^-1^

2. ΔG~298~ = +318.7 kJ mol^-1^, ΔG~523~ = 307.6 kJ mol^-1^

3. [C] = 174 mol dm^-1^ (so big it is essentially all product!)

4. Δ~vap~H = +34.5 kJ mol^-1^, T~b~ = 78 ºC

5. K = 3.649 × 10^29^
 
6. Δ~r~H = -28.0 kJ
